import majors from "./majors.js";
import schools from "./schools.js";

let students = [
    {
        name: '王大虎',
        gender: '男',
        studentId: '20210001',
        mobile: '12345678901',
        school: '信息科学与工程学院',
        major: '计算机科学与技术',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 99,
        },
    },
    {
        name: '王二虎',
        gender: '男',
        studentId: '20210002',
        mobile: '12345678902',
        school: '软件学院',
        major: '软件工程',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
        },
    },
    {
        name: '王小虎',
        gender: '男',
        studentId: '20210003',
        mobile: '12345678903',
        school: '信息科学与工程学院',
        major: '通信工程',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
        },
    },
    {
        name: '张豆',
        gender: '女',
        studentId: '20210004',
        mobile: '12345678904',
        school: '信息科学与工程学院',
        major: '电子信息工程',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
        },
    },
    {
        name: '张豆豆',
        gender: '女',
        studentId: '20210005',
        mobile: '12345678905',
        school: '信息科学与工程学院',
        major: '自动化',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            生物: null,
        },
    },
    {
        name: '张小豆',
        gender: '女',
        studentId: '20210006',
        mobile: '12345678906',
        school: '信息科学与工程学院',
        major: '信息安全',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: 100,
        },
    },
    {
        name: '张大豆',
        gender: '男',
        studentId: '20210007',
        mobile: '12345678907',
        school: '信息科学与工程学院',
        major: '物联网工程',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: null,
            生物: null,
        },
    },
    {
        name: '张二豆',
        gender: '男',
        studentId: '20210008',
        mobile: '12345678908',
        school: '信息科学与工程学院',
        major: '智能科学与技术',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: null,
            生物: null,
        },
    },
    {
        name: '肖美香',
        gender: '女',
        studentId: '20210009',
        mobile: '12345678909',
        school: '信息科学与工程学院',
        major: '测控技术与仪器',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: null,
            生物: null,
        },
    },
    {
        name: '马冬梅',
        gender: '女',
        studentId: '20210010',
        mobile: '12345678910',
        school: '信息科学与工程学院',
        major: '电气工程及其自动化',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: null,
            生物: null,
        },
    },
    {
        name: '丁丁',
        gender: '男',
        studentId: '20210011',
        mobile: '12345678911',
        school: '信息科学与工程学院',
        major: '计算机科学与技术',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: null,
            化学: null,
            生物: null,
        },
    },
    {
        name: '丁小丁',
        gender: '男',
        studentId: '20210012',
        mobile: '12345678912',
        school: '信息科学与工程学院',
        major: '信息安全',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            化学: null,
            生物: null,
        },
    },
    {
        name: '李明',
        gender: '男',
        studentId: '20210013',
        mobile: '12345678913',
        school: '信息科学与工程学院',
        major: '物联网工程',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            生物: null,
        },
    },
    {
        name: '李小明',
        gender: '男',
        studentId: '20210014',
        mobile: '12345678914',
        school: '信息科学与工程学院',
        major: '智能科学与技术',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: null,
            化学: null,
            生物: null,
        },
    },
    {
        name: '赵跑跑',
        gender: '男',
        studentId: '20210015',
        mobile: '12345678915',
        school: '信息科学与工程学院',
        major: '测控技术与仪器',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: null,
            生物: null,
        },
    },
    {
        name: '孙小孙',
        gender: '女',
        studentId: '20210016',
        mobile: '12345678916',
        school: '信息科学与工程学院',
        major: '电气工程及其自动化',
        grades: {
            语文: 90,
            数学: 80,
            英语: 60,
            物理: 100,
            化学: null,
        },
    },
    {
        name: '黄希希',
        gender: '女',
        studentId: '20210017',
        mobile: '12345678917',
        school: '信息科学与工程学院',
        major: '电子信息工程',
        grades: {
            语文: null,
            数学: null,
            英语: null,
        },
    },
]

export default students;